# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Update PIP
      run: python -m pip install --upgrade pip

    - name: Install packages
      run: python -m pip install --user pdm

    - name: Install module (pdm)
      run: python -m pdm install

  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Update PIP
      run: python -m pip install --upgrade pip

    - name: Install packages
      run: python -m pip install --user pdm

    - name: Build module (pdm)
      run: python -m pdm build



